import fs from 'node:fs';
const v5=fs.readFileSync('worker/v5-entry.js','utf8');
const v7=fs.readFileSync('worker/v7-entry.js','utf8');
const app=fs.readFileSync('site/app.js','utf8');
const html=fs.readFileSync('site/index.html','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');
for(const [name,text] of [['v5',v5],['v7',v7],['index',html],['wrangler',wrangler]]) if(text.includes('2030164')) throw new Error(`Public admin username leaked in ${name}`);
if(/\beval\s*\(/.test(app)) throw new Error('eval() is forbidden');
if(!v5.includes('LOGIN_MAX_FAILURES')) throw new Error('login rate limit missing');
if(!v7.includes('reference_reservations')||!v7.includes('claim_drafts')) throw new Error('V7 reservation logic missing');
if(!v7.includes('overallStatus')||!v7.includes('store_cases')||!v7.includes('case_messages')||!v7.includes('notifications')) throw new Error('V7 collaboration logic missing');
if(!v7.includes('toContractRow')) throw new Error('A:AQ export mapping missing');
if(!app.includes('syncReference')||!app.includes('downloadExport')||!app.includes('submitStoreCase')) throw new Error('V7 UI wiring missing');
for(const x of ['Claim Workbench','Store Queue','Export Studio','User Access','STORE CLAIM PORTAL']) if(!html.includes(x)) throw new Error(`Missing V7 UI: ${x}`);
if(!wrangler.includes('worker/v7-entry.js')) throw new Error('wrangler is not on V7');
console.log('V7 security + collaboration contract ok');
