import { createHash, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

const BUILD = '2026-08-21-rewrite-v1';
const COOKIE = 'claim_session';
const TZ = 'Asia/Bangkok';
const ALLOWED_DCS = new Set(['92924','91915','91210','91101']);
const ALLOWED_STATUS = new Set(['Accept','Reject','Pending']);
const ALLOWED_WHO = new Set(['DC','TP']);
const OPTION_CATEGORIES = new Set(['claims_reason','status','who','cause_group','root_cause','check_result','adjust_code','status_sc','remark_list']);
const VALIDATION_LOOKUP_LIMIT = 40;
const MASTER_CHUNK_LIMIT = 20;
const CLAIM_CHUNK_LIMIT = 10;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    try {
      if (url.pathname === '/api/build') return json({status:'ok',build:BUILD,entrypoint:'worker/main.js',assets:'site',database:'claim-center'});
      if (url.pathname === '/api/health') {
        const probe = await env.DB.prepare('SELECT 1 ok').first();
        return json({status: probe?.ok === 1 ? 'ok' : 'error', build: BUILD, time: new Date().toISOString()});
      }
      if (url.pathname.startsWith('/api/')) return await api(request, env, url);
      return assetResponse(await env.ASSETS.fetch(request));
    } catch (error) {
      console.error('Claim Center rewrite error', error);
      return json({status:'error',message:error?.publicMessage || error?.message || 'เกิดข้อผิดพลาดภายในระบบ'}, error?.status || 500);
    }
  }
};

async function api(request, env, url) {
  const method = request.method.toUpperCase();
  if (method === 'OPTIONS') return new Response(null,{status:204});
  if (url.pathname === '/api/auth/login' && method === 'POST') return login(request, env, url);
  if (url.pathname === '/api/auth/logout' && method === 'POST') return logout(request, env, url);
  const user = await requireUser(request, env);
  if (url.pathname === '/api/auth/me' && method === 'GET') return json({status:'success',user:publicUser(user)});
  if (!['GET','HEAD'].includes(method)) checkOrigin(request, url);
  if (url.pathname === '/api/users/me/password' && method === 'POST') return changeOwnPassword(request, env, user);
  if (url.pathname === '/api/users' && method === 'GET') { requireAdmin(user); return listUsers(env); }
  if (url.pathname === '/api/users' && method === 'POST') { requireAdmin(user); return createUser(request, env); }
  if (url.pathname.startsWith('/api/users/') && method === 'DELETE') { requireAdmin(user); return deleteUser(url, env, user); }
  if (url.pathname === '/api/options' && method === 'GET') return listOptions(env);
  if (url.pathname === '/api/options' && method === 'POST') { requireAdmin(user); return addOption(request, env, user); }
  if (url.pathname.startsWith('/api/options/') && method === 'DELETE') { requireAdmin(user); return deleteOption(url, env); }
  if (url.pathname === '/api/dashboard' && method === 'GET') return dashboard(env, url);
  if (url.pathname === '/api/dashboard/rebuild' && method === 'POST') { requireAdmin(user); return rebuildDashboard(env); }
  if (url.pathname === '/api/masters/resolve' && method === 'POST') return resolveMasters(request, env);
  if (url.pathname === '/api/master/stores' && method === 'POST') { requireAdmin(user); return saveStores(request, env); }
  if (url.pathname === '/api/master/stores/missing-from-claims' && method === 'GET') { requireAdmin(user); return missingStores(env); }
  if (url.pathname === '/api/master-article/status' && method === 'GET') { requireAdmin(user); return masterStatus(env); }
  if (url.pathname === '/api/master-article/start' && method === 'POST') { requireAdmin(user); return masterStart(request, env, user); }
  if (url.pathname === '/api/master-article/chunk' && method === 'POST') { requireAdmin(user); return masterChunk(request, env); }
  if (url.pathname === '/api/master-article/finalize' && method === 'POST') { requireAdmin(user); return masterFinalize(request, env); }
  if (url.pathname === '/api/master-article/abort' && method === 'POST') { requireAdmin(user); return masterAbort(request, env); }
  if (url.pathname === '/api/validation/lookup' && method === 'POST') return validationLookup(request, env);
  if (url.pathname === '/api/claims' && method === 'GET') return listClaims(env, url);
  if (url.pathname === '/api/claims/bulk' && method === 'POST') return saveClaims(request, env, user);
  if (url.pathname === '/api/claims/export' && method === 'GET') return exportClaims(env, url);
  if (url.pathname.startsWith('/api/claims/group/') && method === 'GET') return getClaimGroup(env, url);
  if (url.pathname.startsWith('/api/claims/transport/') && method === 'DELETE') { requireAdmin(user); return deleteTransport(env, url); }
  if (url.pathname === '/api/claims/email-status' && method === 'POST') return setEmailStatus(request, env);
  if (url.pathname === '/api/references' && method === 'GET') return listReferences(env, url);
  if (url.pathname === '/api/references' && method === 'POST') { requireAdmin(user); return addReference(request, env); }
  if (url.pathname.startsWith('/api/references/') && method === 'DELETE') { requireAdmin(user); return deleteReference(env, url); }
  if (url.pathname === '/api/performance' && method === 'GET') return performance(env, url);
  if (url.pathname === '/api/history/import' && method === 'POST') { requireAdmin(user); return historyImport(request, env, user); }
  return json({status:'error',message:'ไม่พบ API'},404);
}

async function login(request, env, url) {
  await ensureAdmin(env);
  const body = await readJson(request);
  const username = text(body.username);
  const user = await env.DB.prepare('SELECT * FROM users WHERE username = ? COLLATE NOCASE').bind(username).first();
  if (!user || !verifyPassword(body.password, user.password_hash)) return json({status:'error',message:'ชื่อผู้ใช้งานหรือรหัสผ่านไม่ถูกต้อง'},401);
  const token = randomBytes(32).toString('base64url');
  const tokenHash = sha256(token);
  const maxAge = Math.max(1,Number(env.SESSION_HOURS || 10))*3600;
  const now = Date.now();
  await env.DB.batch([
    env.DB.prepare('DELETE FROM sessions WHERE expires_at <= ?').bind(now),
    env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(tokenHash,user.id,now + maxAge*1000,now)
  ]);
  const response = json({status:'success',user:publicUser(user)});
  response.headers.append('Set-Cookie',cookie(token,maxAge,url.protocol === 'https:'));
  return response;
}
async function logout(request, env, url) {checkOrigin(request,url);const token = readCookie(request);if (token) await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(sha256(token)).run();const response = json({status:'success'});response.headers.append('Set-Cookie',cookie('',0,url.protocol === 'https:'));return response;}
async function requireUser(request, env) {const token = readCookie(request);if (!token) throw publicError(401,'กรุณาเข้าสู่ระบบ');const row = await env.DB.prepare(`SELECT u.id,u.username,u.role,u.created_at,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(sha256(token),Date.now()).first();if (!row) throw publicError(401,'Session หมดอายุ กรุณาเข้าสู่ระบบใหม่');return row;}
function requireAdmin(user){ if(user.role !== 'admin') throw publicError(403,'สิทธิ์ Administrator เท่านั้น'); }
function publicUser(row){ return {id:row.id,username:row.username,role:row.role,createdAt:row.created_at}; }
async function ensureAdmin(env){const existing = await env.DB.prepare('SELECT id FROM users LIMIT 1').first();if(existing) return;if(!env.ADMIN_PASSWORD) throw publicError(503,'ยังไม่ได้ตั้ง Secret: ADMIN_PASSWORD');await env.DB.prepare("INSERT INTO users(username,password_hash,role,created_at) VALUES(?,?,'admin',?)").bind(text(env.ADMIN_USERNAME||'2030164'),hashPassword(env.ADMIN_PASSWORD),bangkokTimestamp()).run();}
function hashPassword(password){ const salt=randomBytes(16); const hash=scryptSync(String(password),salt,64); return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`; }
function verifyPassword(password, stored){ try{ const [scheme,saltHex,hashHex]=String(stored||'').split('$'); if(scheme!=='scrypt') return false; const expected=Buffer.from(hashHex,'hex'); const actual=scryptSync(String(password),Buffer.from(saltHex,'hex'),expected.length); return expected.length===actual.length&&timingSafeEqual(expected,actual);}catch{return false;} }
function strongPassword(value){ const s=String(value||''); return s.length>=10&&/[A-Za-z]/.test(s)&&/\d/.test(s); }
function sha256(value){ return createHash('sha256').update(String(value)).digest('hex'); }
function readCookie(request){ for(const part of (request.headers.get('cookie')||'').split(';')){ const [k,...v]=part.trim().split('='); if(k===COOKIE) return decodeURIComponent(v.join('=')); } return ''; }
function cookie(token,maxAge,secure){ return [`${COOKIE}=${encodeURIComponent(token)}`,'Path=/','HttpOnly','SameSite=Strict',secure?'Secure':'',`Max-Age=${Math.max(0,Math.floor(maxAge))}`].filter(Boolean).join('; '); }
async function changeOwnPassword(request,env,user){ const body=await readJson(request); if(!strongPassword(body.password)) return json({status:'error',message:'รหัสผ่านต้องยาวอย่างน้อย 10 ตัว และมีทั้งตัวอักษรกับตัวเลข'},422); await env.DB.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(hashPassword(body.password),user.id).run(); return json({status:'success'}); }
async function listUsers(env){ const r=await env.DB.prepare('SELECT id,username,role,created_at FROM users ORDER BY username COLLATE NOCASE').all(); return json({status:'success',data:r.results||[]}); }
async function createUser(request,env){ const b=await readJson(request); const username=text(b.username); if(!username) return json({status:'error',message:'กรุณาระบุ Username'},422); if(!strongPassword(b.password)) return json({status:'error',message:'รหัสผ่านต้องยาวอย่างน้อย 10 ตัว และมีทั้งตัวอักษรกับตัวเลข'},422); try{ await env.DB.prepare('INSERT INTO users(username,password_hash,role,created_at) VALUES(?,?,?,?)').bind(username,hashPassword(b.password),b.role==='admin'?'admin':'user',bangkokTimestamp()).run(); }catch(e){ if(String(e.message).includes('UNIQUE')) return json({status:'error',message:'Username นี้มีอยู่แล้ว'},409); throw e; } return json({status:'success'},201); }
async function deleteUser(url,env,current){ const username=decodeURIComponent(url.pathname.split('/').pop()); if(username.toLowerCase()===String(current.username).toLowerCase()) return json({status:'error',message:'ไม่สามารถลบบัญชีที่กำลังใช้งานได้'},422); const r=await env.DB.prepare("DELETE FROM users WHERE username=? COLLATE NOCASE AND role<>'admin'").bind(username).run(); return json({status:Number(r.meta?.changes||0)?'success':'error',message:Number(r.meta?.changes||0)?undefined:'ไม่พบผู้ใช้ หรือบัญชีเป็น Admin'},Number(r.meta?.changes||0)?200:404); }

async function listOptions(env){ const r=await env.DB.prepare('SELECT id,category,value,sort_order FROM dropdown_options ORDER BY category,sort_order,id').all(); const grouped={}; for(const row of r.results||[]){ (grouped[row.category] ||= []).push(row); } return json({status:'success',data:grouped}); }
async function addOption(request,env,user){ const b=await readJson(request); const category=text(b.category), value=text(b.value); if(!OPTION_CATEGORIES.has(category)||!value) return json({status:'error',message:'ข้อมูล Dropdown ไม่ถูกต้อง'},422); const max=await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0) n FROM dropdown_options WHERE category=?').bind(category).first(); try{ await env.DB.prepare('INSERT INTO dropdown_options(category,value,sort_order,created_by,created_at) VALUES(?,?,?,?,?)').bind(category,value,Number(max?.n||0)+10,user.username,bangkokTimestamp()).run(); }catch(e){ if(String(e.message).includes('UNIQUE')) return json({status:'error',message:'รายการนี้มีอยู่แล้ว'},409); throw e; } return listOptions(env); }
async function deleteOption(url,env){ const id=Number(url.pathname.split('/').pop()); const r=await env.DB.prepare('DELETE FROM dropdown_options WHERE id=?').bind(id).run(); return json({status:Number(r.meta?.changes||0)?'success':'error'},Number(r.meta?.changes||0)?200:404); }

async function dashboard(env,url){
  const year=text(url.searchParams.get('year')), month=text(url.searchParams.get('month')), who=text(url.searchParams.get('who')), status=text(url.searchParams.get('status')), format=text(url.searchParams.get('format'));
  const {where,params}=summaryFilter({year,month,who,status,format});
  const s=await env.DB.prepare(`SELECT COUNT(*) total_cases,COALESCE(SUM(total_amount),0) total_amount,COALESCE(AVG(total_amount),0) avg_ticket,SUM(CASE WHEN dominant_status='Accept' THEN 1 ELSE 0 END) accept_cases,SUM(CASE WHEN dominant_status='Pending' THEN 1 ELSE 0 END) pending_cases,SUM(CASE WHEN dominant_status='Reject' THEN 1 ELSE 0 END) reject_cases FROM claim_case_summary ${where}`).bind(...params).first();
  const trend=await env.DB.prepare(`SELECT reply_date date,COUNT(*) cases,COALESCE(SUM(total_amount),0) amount FROM claim_case_summary ${where} GROUP BY reply_date ORDER BY reply_date`).bind(...params).all();
  const formats=await env.DB.prepare(`SELECT COALESCE(NULLIF(format_type,''),'UNKNOWN') name,COUNT(*) cases,COALESCE(SUM(total_amount),0) amount FROM claim_case_summary ${where} GROUP BY format_type ORDER BY cases DESC`).bind(...params).all();
  const topWhere=where.replaceAll('reply_date','c.reply_date').replaceAll('who','c.who').replaceAll('dominant_status','c.dominant_status').replaceAll('format_type','c.format_type');
  const top=await env.DB.prepare(`SELECT c.store_code,COALESCE(s.store_name,'') store_name,COUNT(*) cases,COALESCE(SUM(c.total_amount),0) amount FROM claim_case_summary c LEFT JOIN master_stores s ON s.store_code=c.store_code ${topWhere} GROUP BY c.store_code ORDER BY cases DESC LIMIT 10`).bind(...params).all();
  const recent=await env.DB.prepare(`SELECT * FROM claim_case_summary ${where} ORDER BY updated_at DESC LIMIT 12`).bind(...params).all();
  const total=Number(s?.total_cases||0); const complete=Number(s?.accept_cases||0)+Number(s?.reject_cases||0);
  return json({status:'success',data:{summary:{totalCases:total,totalAmount:Number(s?.total_amount||0),avgTicket:Number(s?.avg_ticket||0),completionRate:total?complete*100/total:0,acceptCases:Number(s?.accept_cases||0),pendingCases:Number(s?.pending_cases||0),rejectCases:Number(s?.reject_cases||0)},trend:trend.results||[],formats:formats.results||[],topStores:top.results||[],recent:recent.results||[]}});
}
function summaryFilter({year,month,who,status,format}){ const c=[],p=[]; if(year&&year!=='all'){c.push("substr(reply_date,1,4)=?");p.push(year);} if(month&&month!=='all'){c.push("CAST(substr(reply_date,6,2) AS INTEGER)=?");p.push(Number(month));} if(who&&who!=='all'){c.push('who=?');p.push(who);} if(status&&status!=='all'){c.push('dominant_status=?');p.push(status);} if(format&&format!=='all'){c.push('format_type=?');p.push(format);} return {where:c.length?`WHERE ${c.join(' AND ')}`:'',params:p}; }
async function rebuildDashboard(env){ await env.DB.prepare('DELETE FROM claim_case_summary').run(); await env.DB.prepare(`INSERT INTO claim_case_summary(transport_no,store_code,reply_date,dominant_status,who,format_type,hub,total_amount,item_count,updated_at) SELECT transport_no,MAX(store_code),MAX(reply_date),CASE WHEN SUM(CASE WHEN update_status='Reject' THEN 1 ELSE 0 END)>0 THEN 'Reject' WHEN SUM(CASE WHEN update_status='Pending' THEN 1 ELSE 0 END)>0 THEN 'Pending' ELSE 'Accept' END,MAX(who),MAX(format_type),MAX(store_type),SUM(amount),COUNT(*),? FROM claims WHERE archived=0 GROUP BY transport_no`).bind(bangkokTimestamp()).run(); const n=await env.DB.prepare('SELECT COUNT(*) n FROM claim_case_summary').first(); return json({status:'success',rebuilt:Number(n?.n||0)}); }
async function refreshCase(env,transport){ const row=await env.DB.prepare(`SELECT transport_no,MAX(store_code) store_code,MAX(reply_date) reply_date,CASE WHEN SUM(CASE WHEN update_status='Reject' THEN 1 ELSE 0 END)>0 THEN 'Reject' WHEN SUM(CASE WHEN update_status='Pending' THEN 1 ELSE 0 END)>0 THEN 'Pending' ELSE 'Accept' END dominant_status,MAX(who) who,MAX(format_type) format_type,MAX(store_type) hub,SUM(amount) total_amount,COUNT(*) item_count FROM claims WHERE archived=0 AND transport_no=? GROUP BY transport_no`).bind(transport).first(); if(!row){ await env.DB.prepare('DELETE FROM claim_case_summary WHERE transport_no=?').bind(transport).run(); return; } await env.DB.prepare(`INSERT INTO claim_case_summary(transport_no,store_code,reply_date,dominant_status,who,format_type,hub,total_amount,item_count,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(transport_no) DO UPDATE SET store_code=excluded.store_code,reply_date=excluded.reply_date,dominant_status=excluded.dominant_status,who=excluded.who,format_type=excluded.format_type,hub=excluded.hub,total_amount=excluded.total_amount,item_count=excluded.item_count,updated_at=excluded.updated_at`).bind(row.transport_no,row.store_code,row.reply_date,row.dominant_status,row.who,row.format_type,row.hub,Number(row.total_amount||0),Number(row.item_count||0),bangkokTimestamp()).run(); }

async function resolveMasters(request,env){ const b=await readJson(request); const articles=unique((b.articles||[]).map(text).filter(Boolean)).slice(0,40), stores=unique((b.stores||[]).map(text).filter(Boolean)).slice(0,80); const data={stores:{},products:{}}; if(stores.length){ const r=await env.DB.prepare(`SELECT * FROM master_stores WHERE store_code IN (${marks(stores.length)})`).bind(...stores).all(); for(const x of r.results||[]) data.stores[x.store_code]=x; } if(articles.length){ const r=await env.DB.prepare(`SELECT * FROM master_products WHERE article IN (${marks(articles.length)}) OR barcode IN (${marks(articles.length)})`).bind(...articles,...articles).all(); for(const x of r.results||[]){ if(x.article) data.products[x.article]=x; if(x.barcode) data.products[x.barcode]=x; } } return json({status:'success',data}); }
async function saveStores(request,env){ const b=await readJson(request,8*1024*1024); const rows=Array.isArray(b.records)?b.records:[]; if(rows.length>500) return json({status:'error',message:'ครั้งละไม่เกิน 500 สาขา'},413); const now=bangkokTimestamp(); let count=0; for(let i=0;i<rows.length;i+=20){ const chunk=rows.slice(i,i+20).map(r=>Array.isArray(r)?{code:text(r[0]),name:text(r[1]),format:text(r[2]),type:text(r[3]),check:text(r[4])}:{code:text(r.storeCode),name:text(r.storeName),format:text(r.formatType),type:text(r.storeType),check:text(r.check100)}).filter(r=>r.code); if(!chunk.length) continue; const values=chunk.map(()=>'(?,?,?,?,?,?)').join(','); await env.DB.prepare(`INSERT INTO master_stores(store_code,store_name,format_type,store_type,check_100,updated_at) VALUES ${values} ON CONFLICT(store_code) DO UPDATE SET store_name=excluded.store_name,format_type=excluded.format_type,store_type=excluded.store_type,check_100=excluded.check_100,updated_at=excluded.updated_at`).bind(...chunk.flatMap(r=>[r.code,r.name,r.format,r.type,r.check,now])).run(); count+=chunk.length; } return json({status:'success',count}); }
async function missingStores(env){ const r=await env.DB.prepare(`SELECT DISTINCT c.store_code FROM claims c LEFT JOIN master_stores s ON s.store_code=c.store_code WHERE c.store_code<>'' AND s.store_code IS NULL ORDER BY c.store_code LIMIT 500`).all(); return json({status:'success',missing:(r.results||[]).map(x=>x.store_code)}); }
async function masterStatus(env){ const row=await env.DB.prepare(`SELECT b.*,(SELECT COUNT(*) FROM master_articles a WHERE a.batch_id=b.batch_id) article_count,(SELECT COUNT(*) FROM master_articles a WHERE a.batch_id=b.batch_id AND a.item_value>0) priced_count FROM master_article_state s LEFT JOIN master_article_batches b ON b.batch_id=s.active_batch_id WHERE s.id=1`).first(); if(!row?.batch_id) return json({status:'success',data:{active:false,articleCount:0,pricedCount:0}}); return json({status:'success',data:{active:true,batchId:row.batch_id,sourceFile:row.source_file,sheetName:row.sheet_name,expectedRows:Number(row.expected_rows||0),receivedRows:Number(row.received_rows||0),articleCount:Number(row.article_count||0),pricedCount:Number(row.priced_count||0),duplicateRows:Math.max(0,Number(row.expected_rows||0)-Number(row.article_count||0)),activatedAt:row.activated_at||''}}); }
async function masterStart(request,env,user){ const b=await readJson(request); const fileName=text(b.fileName), sheetName=text(b.sheetName)||'MasterArticle', totalRows=Number.parseInt(b.totalRows,10); if(!fileName||!Number.isInteger(totalRows)||totalRows<1) return json({status:'error',message:'ข้อมูลไฟล์ MasterArticle ไม่ถูกต้อง'},422); const h=b.headers||[]; if(text(h[0]).toUpperCase()!=='ARTICLE'||text(h[35]).toUpperCase()!=='ITEM_VALUE') return json({status:'error',message:'หัวคอลัมน์ไม่ตรง: A ต้องเป็น ARTICLE และ AJ ต้องเป็น ITEM_VALUE'},422); const batchId=`MA-${Date.now()}-${crypto.randomUUID().replaceAll('-','').slice(0,8)}`; const old=await env.DB.prepare("SELECT batch_id FROM master_article_batches WHERE status='uploading'").all(); for(const x of old.results||[]) await env.DB.batch([env.DB.prepare('DELETE FROM master_articles WHERE batch_id=?').bind(x.batch_id),env.DB.prepare('DELETE FROM master_article_batches WHERE batch_id=?').bind(x.batch_id)]); await env.DB.prepare("INSERT INTO master_article_batches(batch_id,source_file,sheet_name,expected_rows,received_rows,status,created_by,created_at,activated_at) VALUES(?,?,?,?,0,'uploading',?,?, '')").bind(batchId,fileName,sheetName,totalRows,user.username,bangkokTimestamp()).run(); return json({status:'success',batchId,chunkLimit:MASTER_CHUNK_LIMIT},201); }
async function masterChunk(request,env){ const b=await readJson(request,2*1024*1024); const batchId=text(b.batchId), rows=Array.isArray(b.rows)?b.rows:[]; if(!batchId||!rows.length||rows.length>MASTER_CHUNK_LIMIT) return json({status:'error',message:`MasterArticle ครั้งละ 1-${MASTER_CHUNK_LIMIT} แถว`},422); const batch=await env.DB.prepare("SELECT * FROM master_article_batches WHERE batch_id=? AND status='uploading'").bind(batchId).first(); if(!batch) return json({status:'error',message:'Batch ไม่พร้อมอัปโหลด'},409); const now=bangkokTimestamp(); const statements=[]; for(const raw of rows){ if(!Array.isArray(raw)||raw.length<40) return json({status:'error',message:'MasterArticle ต้องมีคอลัมน์อย่างน้อย A:AN'},422); const article=text(raw[0]).replaceAll("'",''); if(!article) continue; statements.push(env.DB.prepare(`INSERT OR IGNORE INTO master_articles(batch_id,article,barcode,description,manage_weight,item_value,seg_description,raw_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(batchId,article,text(raw[3]).replaceAll("'",''),text(raw[4]),text(raw[11]),number(raw[35]),text(raw[39]),JSON.stringify(raw),now)); } statements.push(env.DB.prepare('UPDATE master_article_batches SET received_rows=received_rows+? WHERE batch_id=?').bind(rows.length,batchId)); await env.DB.batch(statements); const p=await env.DB.prepare(`SELECT received_rows,expected_rows,(SELECT COUNT(*) FROM master_articles WHERE batch_id=?) article_count FROM master_article_batches WHERE batch_id=?`).bind(batchId,batchId).first(); return json({status:'success',receivedRows:Number(p?.received_rows||0),expectedRows:Number(p?.expected_rows||0),articleCount:Number(p?.article_count||0)}); }
async function masterFinalize(request,env){ const b=await readJson(request); const batchId=text(b.batchId); const batch=await env.DB.prepare("SELECT * FROM master_article_batches WHERE batch_id=? AND status='uploading'").bind(batchId).first(); if(!batch) return json({status:'error',message:'Batch ไม่พร้อม Finalize'},409); if(Number(batch.received_rows)!==Number(batch.expected_rows)) return json({status:'error',message:`อัปโหลดไม่ครบ ${batch.received_rows}/${batch.expected_rows}`},422); const count=await env.DB.prepare('SELECT COUNT(*) n FROM master_articles WHERE batch_id=?').bind(batchId).first(); if(!Number(count?.n||0)) return json({status:'error',message:'ไม่มี Article ใน Batch'},422); const now=bangkokTimestamp(); const active=await env.DB.prepare('SELECT active_batch_id FROM master_article_state WHERE id=1').first(); await env.DB.batch([env.DB.prepare("UPDATE master_article_batches SET status='replaced' WHERE status='active' AND batch_id<>?").bind(batchId),env.DB.prepare("UPDATE master_article_batches SET status='active',activated_at=? WHERE batch_id=?").bind(now,batchId),env.DB.prepare(`INSERT INTO master_article_state(id,active_batch_id,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET active_batch_id=excluded.active_batch_id,updated_at=excluded.updated_at`).bind(batchId,now)]); if(active?.active_batch_id&&active.active_batch_id!==batchId){ await env.DB.prepare('DELETE FROM master_articles WHERE batch_id=?').bind(active.active_batch_id).run(); await env.DB.prepare('DELETE FROM master_article_batches WHERE batch_id=?').bind(active.active_batch_id).run(); } return masterStatus(env); }
async function masterAbort(request,env){ const b=await readJson(request); const id=text(b.batchId); await env.DB.batch([env.DB.prepare('DELETE FROM master_articles WHERE batch_id=?').bind(id),env.DB.prepare("DELETE FROM master_article_batches WHERE batch_id=? AND status='uploading'").bind(id)]); return json({status:'success'}); }

async function validationLookup(request,env){ const b=await readJson(request,512*1024); const pairs=Array.isArray(b.pairs)?b.pairs:[]; if(pairs.length>VALIDATION_LOOKUP_LIMIT) return json({status:'error',message:`ครั้งละไม่เกิน ${VALIDATION_LOOKUP_LIMIT} คู่`},413); const normalized=[]; const seen=new Set(); for(const p of pairs){ const article=text(p.article).replaceAll("'",''),reference=text(p.reference); const key=`${article.toLowerCase()}\u0000${reference.toLowerCase()}`; if((article||reference)&&!seen.has(key)){seen.add(key);normalized.push({article,reference,key});}} if(!normalized.length) return json({status:'success',data:{}}); const where=normalized.map(()=>'(article=? COLLATE NOCASE AND reference_no=? COLLATE NOCASE)').join(' OR '); const q=await env.DB.prepare(`SELECT article,reference_no,transport_no,vehicle_no,driver,reply_date,claim_no,id FROM claims WHERE ${where} ORDER BY id ASC`).bind(...normalized.flatMap(x=>[x.article,x.reference])).all(); const data={}; for(const r of q.results||[]){ const key=`${text(r.article).toLowerCase()}\u0000${text(r.reference_no).toLowerCase()}`; if(!data[key]) data[key]={transportNo:r.transport_no||'-',vehicleNo:r.vehicle_no||'-',driver:r.driver||'-',claimDate:r.reply_date||'-',claimNo:r.claim_no||'-'}; } return json({status:'success',data}); }

async function listClaims(env,url){ const transport=text(url.searchParams.get('transport')),article=text(url.searchParams.get('article')),store=text(url.searchParams.get('store')),date=text(url.searchParams.get('date')),reference=text(url.searchParams.get('reference')); const c=['archived=0'],p=[]; for(const [col,val] of [['transport_no',transport],['article',article],['store_code',store],['reply_date',date],['reference_no',reference]]) if(val){c.push(`${col}=?`);p.push(val);} const limit=Math.min(300,Math.max(20,Number(url.searchParams.get('limit')||120))); const r=await env.DB.prepare(`SELECT * FROM claims WHERE ${c.join(' AND ')} ORDER BY id DESC LIMIT ?`).bind(...p,limit).all(); const groups=groupClaims(r.results||[]); return json({status:'success',groups,totalGroups:groups.length}); }
function groupClaims(rows){ const m=new Map(); for(const r of rows){ const key=`${r.transport_no}|${r.update_status}|${r.who}`; if(!m.has(key))m.set(key,{key,transportNo:r.transport_no,status:r.update_status,who:r.who,storeCode:r.store_code,storeName:r.store_name,claimNo:r.claim_no,referenceNo:r.reference_no,totalAmount:0,emailSent:false,rows:[]}); const g=m.get(key); g.rows.push(apiClaim(r));g.totalAmount+=Number(r.amount||0);g.emailSent ||= Boolean(r.email_sent);} return [...m.values()]; }
async function getClaimGroup(env,url){ const transport=decodeURIComponent(url.pathname.split('/').pop()); const status=text(url.searchParams.get('status')),who=text(url.searchParams.get('who')); const c=['transport_no=?'],p=[transport]; if(status){c.push('update_status=?');p.push(status);} if(who){c.push('who=?');p.push(who);} const r=await env.DB.prepare(`SELECT * FROM claims WHERE ${c.join(' AND ')} ORDER BY id`).bind(...p).all(); return json({status:'success',rows:(r.results||[]).map(apiClaim)}); }
async function saveClaims(request,env,user){ const b=await readJson(request,2*1024*1024); const source=Array.isArray(b.rows)?b.rows:[]; if(!source.length) return json({status:'error',message:'ไม่พบข้อมูล'},422); if(source.length>CLAIM_CHUNK_LIMIT) return json({status:'error',message:`บันทึกครั้งละไม่เกิน ${CLAIM_CHUNK_LIMIT} แถว`},413); const rows=source.map(normalizeClaim); const errors=[]; rows.forEach((r,i)=>{const e=validateClaim(r,Boolean(b.bypassDate));if(e.length)errors.push({row:i+1,errors:e});}); if(errors.length) return json({status:'error',message:'ข้อมูลไม่ผ่านการตรวจสอบ',details:errors},422);
  const storeCodes=unique(rows.map(x=>x.storeCode)), productKeys=unique(rows.flatMap(x=>[x.article,x.barcode]).filter(Boolean)), refs=unique(rows.map(x=>x.refId).filter(Boolean)), transports=unique(rows.map(x=>x.transportNo));
  const stores=storeCodes.length?(await env.DB.prepare(`SELECT * FROM master_stores WHERE store_code IN (${marks(storeCodes.length)})`).bind(...storeCodes).all()).results||[]:[];
  const products=productKeys.length?(await env.DB.prepare(`SELECT * FROM master_products WHERE article IN (${marks(productKeys.length)}) OR barcode IN (${marks(productKeys.length)})`).bind(...productKeys,...productKeys).all()).results||[]:[];
  const existing=refs.length?(await env.DB.prepare(`SELECT * FROM claims WHERE ref_id IN (${marks(refs.length)})`).bind(...refs).all()).results||[]:[];
  const previous=transports.length?(await env.DB.prepare(`SELECT transport_no,update_status,reply_date,who,claim_no,reference_no FROM claims WHERE transport_no IN (${marks(transports.length)}) ORDER BY id DESC`).bind(...transports).all()).results||[]:[];
  const sm=new Map(stores.map(x=>[x.store_code,x])), pm=new Map(); for(const p of products){if(p.article)pm.set(p.article,p);if(p.barcode)pm.set(p.barcode,p);} const em=new Map(existing.map(x=>[x.ref_id,x])); const claimMap=new Map(),refMap=new Map(),prevClaim=new Map(),prevRef=new Map(); for(const x of previous){ const ck=`${x.transport_no}|${x.update_status}|${x.reply_date}`; if(x.claim_no&&!prevClaim.has(ck))prevClaim.set(ck,x.claim_no); const rk=`${x.who}|${x.transport_no}`; if(x.reference_no&&x.reference_no!=='-'&&!prevRef.has(rk))prevRef.set(rk,x.reference_no); }
  const now=bangkokTimestamp(); let inserted=0,updated=0; const affected=new Set();
  for(const row of rows){ const ex=row.refId?em.get(row.refId):null; if(row.refId&&!ex) return json({status:'error',message:`ไม่พบ Ref ID ${row.refId}`},404); if(!ex){ const dup=await env.DB.prepare('SELECT id FROM claims WHERE archived=0 AND lower(transport_no)=lower(?) AND lower(article)=lower(?) LIMIT 1').bind(row.transportNo,row.article).first(); if(dup) return json({status:'error',message:`สินค้า ${row.article} ในรอบรถ ${row.transportNo} มีอยู่แล้ว`},409); }
    const s=sm.get(row.storeCode)||{}, p=pm.get(row.article)||pm.get(row.barcode)||{}; if(p.article&&row.barcode&&p.article!==row.article)row.article=p.article; if(!row.barcode&&p.barcode)row.barcode=p.barcode; row.formatType=formatType(row.storeCode,s.format_type);row.storeType=text(s.store_type);row.check100=text(s.check_100);row.listEggs=text(p.list_eggs);row.manageWeight=text(p.manage_weight);row.segDescription=text(p.seg_description);row.skuCost=ex?Number(ex.sku_cost||0):Number(p.sku_cost||row.skuCost||0); if(row.amountInput===false)row.amount=row.skuCost*number(row.claimQty); row.finalStatus=['Accept','Reject'].includes(row.status)?'Complete':'Pending';
    if(ex){row.refId=ex.ref_id;row.claimNo=ex.claim_no;row.referenceNo=existingReference(row,ex);row.createdBy=ex.created_by;row.createdAt=ex.created_at;row.emailSent=Boolean(ex.email_sent);row.updatedAt=now;row.updatedBy=user.username;await updateClaim(env,row);updated++;}
    else{row.refId=makeRefId();row.claimNo=await claimNumber(env,row,claimMap,prevClaim);row.referenceNo=await referenceNumber(env,row,refMap,prevRef);row.createdBy=user.username;row.createdAt=now;row.updatedAt='';row.updatedBy='';row.emailSent=false;await insertClaim(env,row);inserted++;}
    if(row.status==='Accept'&&row.referenceNo&&row.referenceNo!=='-'&&['DC','TP'].includes(row.who)) await env.DB.prepare(`INSERT OR IGNORE INTO claim_references(ref_no,reference_type,reply_date,claim_no,store_code,remark,source_label,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(row.referenceNo,row.who,row.replyDate,row.claimNo,row.storeCode,row.reason,row.who==='DC'?'DC':'Transport Accept',now).run(); affected.add(row.transportNo);
  }
  for(const t of affected) await refreshCase(env,t); return json({status:'success',count:rows.length,inserted,updated}); }
function normalizeClaim(src){ const r={...src}; for(const k of Object.keys(r)) if(typeof r[k]==='string')r[k]=r[k].trim(); r.storeCode=digits(r.storeCode);r.claimDc=digits(r.claimDc).slice(0,5);r.article=text(r.article).replaceAll("'",'');r.barcode=text(r.barcode).replaceAll("'",'');r.receivedDate=dateIso(r.receivedDate);r.reportedDate=dateIso(r.reportedDate);r.replyDate=dateIso(r.replyDate);r.palletNo=text(r.palletNo).replace(/80000000/g,'').replace(/[,:]/g,'').trim();r.basketNo='';r.amountInput=!(r.amount===''||r.amount===null||r.amount===undefined);r.amount=number(r.amount);r.skuCost=number(r.skuCost);r.sentQty=numericText(r.sentQty);r.receivedQty=numericText(r.receivedQty);r.claimQty=numericText(r.claimQty);return r; }
function validateClaim(r,bypass){ const e=[]; if(!/^\d{5}$/.test(r.storeCode)||!['1','2','3','7'].includes(r.storeCode[0]))e.push('Store Code ไม่ถูกต้อง'); if(r.claimDc&&!ALLOWED_DCS.has(r.claimDc))e.push('Claim DC ไม่ถูกต้อง'); if(!/^\d+$/.test(r.transportNo||''))e.push('Transport No. ต้องเป็นตัวเลข'); if(/\d/.test(r.driver||''))e.push('Driver ห้ามมีตัวเลข'); if(!/^1\d{8}$/.test(r.article||''))e.push('Article ต้องเป็น 9 หลักและขึ้นต้นด้วย 1'); if(r.barcode&&!/^\d+$/.test(r.barcode))e.push('Barcode ต้องเป็นตัวเลข'); if(!r.replyDate)e.push('ต้องระบุวันที่ตอบกลับสาขา'); if(!ALLOWED_STATUS.has(r.status))e.push('Status ต้องเป็น Accept/Reject/Pending'); if(!ALLOWED_WHO.has(r.who))e.push('WHO ไม่ถูกต้อง'); if(!text(r.rootCause))e.push('ROOT CAUSE ห้ามว่าง'); if(!text(r.checkResult))e.push('Check ห้ามว่าง'); if(!bypass&&r.replyDate){const d=new Date(`${r.replyDate}T00:00:00+07:00`),today=new Date(`${todayIso()}T00:00:00+07:00`),min=new Date(today);min.setDate(min.getDate()-15);if(d.getFullYear()!==today.getFullYear())e.push('วันที่ตอบกลับต้องอยู่ในปีปัจจุบัน');if(d<min)e.push('วันที่ตอบกลับย้อนหลังเกิน 15 วัน');} return e; }
async function claimNumber(env,row,map,prev){ const prefix=row.formatType==='HYPER'?'HYP':row.formatType==='MBC'?'MBC':row.formatType==='FRANCHISE'?'FC':text(row.formatType).slice(0,3); const date=row.replyDate?`${row.replyDate.slice(8,10)}${row.replyDate.slice(5,7)}${row.replyDate.slice(2,4)}`:''; if(!prefix||!date)return''; const group=`${row.transportNo}|${row.status}|${row.replyDate}`; if(map.has(group))return map.get(group); if(prev.has(group)){map.set(group,prev.get(group));return prev.get(group);} const next=await reserve(env,`CLAIM:${prefix}${date}`); const v=`${prefix}${date}${String(next).padStart(prefix==='HYP'?7:6,'0')}`;map.set(group,v);return v; }
async function referenceNumber(env,row,map,prev){ if(row.status!=='Accept'||!['DC','TP'].includes(row.who))return'-';const prefix=row.who==='DC'?'CCD':'TF',key=`${row.who}|${row.transportNo}`;if(prev.has(key)){const v=prev.get(key);map.set(key,v);return v;}if(map.has(key))return map.get(key);const next=await reserve(env,`REF:${prefix}`);const v=`${prefix}${String(next).padStart(7,'0')}`;map.set(key,v);return v; }
function existingReference(row,ex){ if(row.status!=='Accept'||!['DC','TP'].includes(row.who))return'-';return text(ex.reference_no)||'-'; }
async function reserve(env,key){ const r=await env.DB.prepare(`INSERT INTO sequences(sequence_key,current_value) VALUES(?,1) ON CONFLICT(sequence_key) DO UPDATE SET current_value=current_value+1 RETURNING current_value`).bind(key).first();return Number(r?.current_value||1); }
async function insertClaim(env,r){ const o=dbRow(r); const cols=Object.keys(o); await env.DB.prepare(`INSERT INTO claims(${cols.join(',')}) VALUES(${marks(cols.length)})`).bind(...cols.map(k=>o[k])).run(); }
async function updateClaim(env,r){ const o=dbRow(r); const cols=Object.keys(o).filter(k=>!['ref_id','created_at'].includes(k)); await env.DB.prepare(`UPDATE claims SET ${cols.map(k=>`${k}=?`).join(',')} WHERE ref_id=?`).bind(...cols.map(k=>o[k]),r.refId).run(); }
function dbRow(r){ const [y,m]=r.replyDate? r.replyDate.split('-').map(Number):[0,0]; return {store_code:r.storeCode||'',store_name:r.storeName||'',claim_dc:r.claimDc||'',received_date:r.receivedDate||'',reported_date:r.reportedDate||'',transport_no:r.transportNo||'',vehicle_no:r.vehicleNo||'',driver:r.driver||'',dn_no:r.dnNo||'',route:r.route||'',pallet_no:r.palletNo||'',basket_no:r.basketNo||'',article:r.article||'',barcode:r.barcode||'',description:r.description||'',sent_qty:r.sentQty||'',received_qty:r.receivedQty||'',claim_qty:r.claimQty||'',reason:r.reason||'',amount:Number(r.amount||0),reply_date:r.replyDate||'',update_status:r.status||'',who:r.who||'',format_type:r.formatType||'',store_type:r.storeType||'',claim_no:r.claimNo||'',reference_no:r.referenceNo||'-',final_status:r.finalStatus||'',root_cause:r.rootCause||'',check_result:r.checkResult||'',remark:r.remark||'',list_eggs:r.listEggs||'',check_100:r.check100||'',manage_weight:r.manageWeight||'',sc:r.sc||'',complete_sc:r.completeSc||'',store_check_100:r.storeCheck100||'',sku_cost:Number(r.skuCost||0),seg_description:r.segDescription||'',created_by:r.createdBy||'',ref_id:r.refId||'',updated_at:r.updatedAt||'',updated_by:r.updatedBy||'',email_sent:r.emailSent?1:0,archived:0,created_at:r.createdAt||'',cause_group:r.causeGroup||'',remark_list:r.remarkList||'',unique_key:r.uniqueKey||`${r.transportNo}|${r.article}`,data_month:m||0,data_year:y||0}; }
function apiClaim(r){ return {id:r.id,storeCode:r.store_code,storeName:r.store_name,claimDc:r.claim_dc,receivedDate:r.received_date,reportedDate:r.reported_date,transportNo:r.transport_no,vehicleNo:r.vehicle_no,driver:r.driver,dnNo:r.dn_no,route:r.route,palletNo:r.pallet_no,basketNo:r.basket_no,article:r.article,barcode:r.barcode,description:r.description,sentQty:r.sent_qty,receivedQty:r.received_qty,claimQty:r.claim_qty,reason:r.reason,amount:Number(r.amount||0),replyDate:r.reply_date,status:r.update_status,who:r.who,formatType:r.format_type,storeType:r.store_type,claimNo:r.claim_no,referenceNo:r.reference_no,finalStatus:r.final_status,causeGroup:r.cause_group||'',rootCause:r.root_cause,checkResult:r.check_result,remarkList:r.remark_list||'',remark:r.remark,listEggs:r.list_eggs,check100:r.check_100,manageWeight:r.manage_weight,sc:r.sc,completeSc:r.complete_sc,storeCheck100:r.store_check_100,skuCost:Number(r.sku_cost||0),segDescription:r.seg_description,createdBy:r.created_by,refId:r.ref_id,updatedAt:r.updated_at,updatedBy:r.updated_by,emailSent:Boolean(r.email_sent),createdAt:r.created_at}; }
async function deleteTransport(env,url){ const t=decodeURIComponent(url.pathname.split('/').pop()); const r=await env.DB.prepare('DELETE FROM claims WHERE transport_no=?').bind(t).run(); await env.DB.prepare('DELETE FROM claim_case_summary WHERE transport_no=?').bind(t).run(); return json({status:'success',deleted:Number(r.meta?.changes||0)}); }
async function setEmailStatus(request,env){ const b=await readJson(request); const r=await env.DB.prepare('UPDATE claims SET email_sent=? WHERE transport_no=?').bind(b.checked?1:0,text(b.transportNo)).run(); return json({status:'success',updated:Number(r.meta?.changes||0)}); }
async function exportClaims(env,url){ const c=[],p=[]; const start=text(url.searchParams.get('startDate')),end=text(url.searchParams.get('endDate'));if(start){c.push('reply_date>=?');p.push(start);}if(end){c.push('reply_date<=?');p.push(end);}const status=text(url.searchParams.get('status')),format=text(url.searchParams.get('format'));if(status&&status!=='all'){c.push('update_status=?');p.push(status);}if(format&&format!=='all'){c.push('format_type=?');p.push(format);} const r=await env.DB.prepare(`SELECT * FROM claims ${c.length?'WHERE '+c.join(' AND '):''} ORDER BY id`).bind(...p).all(); return json({status:'success',rows:(r.results||[]).map(apiClaim)}); }

async function listReferences(env,url){ const type=text(url.searchParams.get('type')).toUpperCase()==='TP'?'TP':'DC'; const r=await env.DB.prepare('SELECT * FROM claim_references WHERE reference_type=? ORDER BY id DESC LIMIT 1000').bind(type).all(); return json({status:'success',data:r.results||[]}); }
async function addReference(request,env){ const b=await readJson(request); const type=b.type==='TP'?'TP':'DC'; if(!text(b.refNo))return json({status:'error',message:'กรุณาระบุ Reference'},422); try{await env.DB.prepare(`INSERT INTO claim_references(ref_no,reference_type,reply_date,claim_no,store_code,remark,source_label,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(text(b.refNo),type,dateIso(b.replyDate),text(b.claimNo),text(b.storeCode),text(b.remark),type==='DC'?'DC':'Transport Accept',bangkokTimestamp()).run();}catch(e){if(String(e.message).includes('UNIQUE'))return json({status:'error',message:'Reference นี้มีอยู่แล้ว'},409);throw e;} const m=text(b.refNo).match(type==='DC'?/^(?:CDC|CCD)(\d{7})$/:/^TF(\d{7})$/); if(m) await env.DB.prepare(`INSERT INTO sequences(sequence_key,current_value) VALUES(?,?) ON CONFLICT(sequence_key) DO UPDATE SET current_value=MAX(current_value,excluded.current_value)`).bind(type==='DC'?'REF:CCD':'REF:TF',Number(m[1])).run(); return json({status:'success'}); }
async function deleteReference(env,url){ const parts=url.pathname.split('/'); const ref=decodeURIComponent(parts.pop()),type=decodeURIComponent(parts.pop()).toUpperCase()==='TP'?'TP':'DC'; const r=await env.DB.prepare('DELETE FROM claim_references WHERE reference_type=? AND ref_no=?').bind(type,ref).run(); return json({status:'success',deleted:Number(r.meta?.changes||0)}); }
async function performance(env,url){ const d=text(url.searchParams.get('date')); const p=d?[d]:[]; const n=await env.DB.prepare(`SELECT created_by user,COUNT(DISTINCT transport_no) count FROM claims ${d?'WHERE reply_date=?':''} GROUP BY created_by`).bind(...p).all(); const u=await env.DB.prepare(`SELECT updated_by user,COUNT(DISTINCT transport_no) count FROM claims WHERE updated_by<>'' ${d?'AND substr(updated_at,1,10)=?':''} GROUP BY updated_by`).bind(...p).all(); const m=new Map(); const ensure=x=>{if(!m.has(x))m.set(x,{user:x,newCount:0,updateCount:0,total:0});return m.get(x)};for(const r of n.results||[]){const x=ensure(r.user);x.newCount=Number(r.count);x.total+=Number(r.count);}for(const r of u.results||[]){const x=ensure(r.user);x.updateCount=Number(r.count);x.total+=Number(r.count);}return json({status:'success',data:[...m.values()].sort((a,b)=>b.total-a.total)}); }
async function historyImport(request,env,user){ const b=await readJson(request,5*1024*1024); const rows=Array.isArray(b.rows)?b.rows:[]; if(!rows.length)return json({status:'error',message:'ไม่พบข้อมูลนำเข้า'},422); if(rows.length>100) return json({status:'error',message:'นำเข้าครั้งละไม่เกิน 100 แถว'},413); let inserted=0,ignored=0; const now=bangkokTimestamp(); for(const a of rows){ if(!Array.isArray(a)||a.length<43){ignored++;continue;} const r={storeCode:digits(a[0]),storeName:text(a[1]),claimDc:digits(a[2]),receivedDate:dateIso(a[3]),reportedDate:dateIso(a[4]),transportNo:text(a[5]),vehicleNo:text(a[6]),driver:text(a[7]),dnNo:text(a[8]),route:text(a[9]),palletNo:text(a[10]),basketNo:text(a[11]),article:text(a[12]).replaceAll("'",''),barcode:text(a[13]).replaceAll("'",''),description:text(a[14]),sentQty:numericText(a[15]),receivedQty:numericText(a[16]),claimQty:numericText(a[17]),reason:text(a[18]),amount:number(a[19]),replyDate:dateIso(a[20]),status:text(a[21]),who:text(a[22]),formatType:text(a[23]),claimNo:text(a[24]),referenceNo:text(a[25])||'-',causeGroup:text(a[26]),rootCause:text(a[27]),checkResult:text(a[28]),remarkList:text(a[29]),listEggs:text(a[30]),storeType:text(a[31]),manageWeight:text(a[32]),sc:text(a[33]),completeSc:text(a[34]),remark:text(a[35]),storeCheck100:text(a[36]),skuCost:number(a[37]),segDescription:text(a[38]),createdBy:text(a[39])||user.username,uniqueKey:text(a[40]),dataMonth:Number(a[41]||0),dataYear:Number(a[42]||0),refId:text(a[40])||makeRefId(),createdAt:now,updatedAt:'',updatedBy:'',emailSent:false,check100:'',finalStatus:['Accept','Reject'].includes(text(a[21]))?'Complete':'Pending'}; try{await insertClaim(env,r);inserted++;await refreshCase(env,r.transportNo);}catch(e){if(String(e.message).includes('UNIQUE'))ignored++;else throw e;} } return json({status:'success',inserted,ignored}); }

function checkOrigin(request,url){ const origin=request.headers.get('Origin'); if(origin&&origin!==url.origin) throw publicError(403,'Origin ไม่ถูกต้อง'); }
function assetResponse(response){ const h=new Headers(response.headers);h.set('x-claim-build',BUILD);h.set('x-content-type-options','nosniff');h.set('referrer-policy','same-origin'); if((h.get('content-type')||'').includes('text/html'))h.set('cache-control','no-store'); return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h}); }
function json(body,status=200){ return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-claim-build':BUILD,'x-content-type-options':'nosniff'}}); }
async function readJson(request,limit=1024*1024){ const len=Number(request.headers.get('content-length')||0); if(len>limit)throw publicError(413,'ข้อมูลมีขนาดใหญ่เกินกำหนด'); const txt=await request.text(); if(txt.length>limit)throw publicError(413,'ข้อมูลมีขนาดใหญ่เกินกำหนด'); try{return txt?JSON.parse(txt):{};}catch{throw publicError(400,'JSON ไม่ถูกต้อง');} }
function publicError(status,message){ const e=new Error(message);e.status=status;e.publicMessage=message;return e; }
function text(v){return v==null?'':String(v).trim();} function digits(v){return text(v).replace(/\D/g,'');} function number(v){const n=Number.parseFloat(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0;} function numericText(v){const s=text(v);if(!s)return'';const n=Number.parseFloat(s.replace(/,/g,''));return Number.isFinite(n)?String(n):s;} function unique(a){return [...new Set(a)];} function marks(n){return Array.from({length:n},()=>'?').join(',');}
function formatType(store,fallback=''){const s=text(store);if(s.startsWith('1'))return'HYPER';if(s.startsWith('2'))return'MBC';if(s.startsWith('3'))return'FRANCHISE';return text(fallback).toUpperCase();}
function dateIso(v){const s=text(v);if(!s)return'';let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
function todayIso(){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function bangkokTimestamp(){return new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date());}
function makeRefId(){const d=new Date();const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'2-digit',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(d).map(x=>[x.type,x.value]));return`CLM-${p.year}${p.month}${p.day}${p.hour}${p.minute}${p.second}-${crypto.randomUUID().replaceAll('-','').slice(0,10)}`;}
