import { createHash, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

const BUILD='2026-08-22-security-hardening-v6';
const COOKIE='claim_session';
const HEADERS=['Store Code','Store Name (Thai)','Claim DC','Received Date','Claim Date','Transport No.','VehicleNo.','Driver','DN No.','Route','Pallet No.','Basket No.','Article','Barcode','Description','Delivery Qty (PU/Kg)','Received QTY (PU/Kg)','Claim Qty (PU/Kg)','Claims Reason','Amount claim','Ship Date','Update status','WHO','Format Type','Claim NO','Reference_No.','Cause Group','ROOT CAUSE','Check','Remark List','Eggs','Format Type','MANAGE_WEIGHT','SC','Complet SC','Remark','Store Hyper เช็ค 100 %','SKU_cost','SEG_DESCRIPTION','ผู้บันทึกข้อมูล','Unique Key','Month','Year'];
const CATS=new Set(['claims_reason','status','who','cause_group','root_cause','check_result','adjust_code','status_sc','remark_list']);

export { HEADERS as CLAIM_HEADERS };
export default {async fetch(request,env){
  const url=new URL(request.url);
  try{
    if(url.pathname==='/api/build')return json({status:'success',build:BUILD,contract:'A:AQ 43 columns',worker:'worker/v5-entry.js',security:'rate-limit+origin+money-rounding'});
    if(url.pathname==='/api/health'){const x=await env.DB.prepare('SELECT 1 ok').first();return json({status:x?.ok===1?'success':'error',build:BUILD,time:now()});}
    if(url.pathname.startsWith('/api/'))return await api(request,env,url);
    const r=await env.ASSETS.fetch(request);return noStore(r);
  }catch(e){console.error(e);return json({status:'error',message:e?.publicMessage||e?.message||'Internal error'},e?.status||500);}
}};

async function api(req,env,url){
  const m=req.method.toUpperCase();
  if(m==='OPTIONS')return new Response(null,{status:204});
  if(url.pathname==='/api/auth/login'&&m==='POST'){checkOrigin(req,url);return login(req,env,url);}
  if(url.pathname==='/api/auth/logout'&&m==='POST'){checkOrigin(req,url);return logout(req,env,url);}
  const user=await requireUser(req,env);
  if(url.pathname==='/api/auth/me'&&m==='GET')return json({status:'success',user:publicUser(user)});
  if(!['GET','HEAD'].includes(m))checkOrigin(req,url);

  if(url.pathname==='/api/dashboard'&&m==='GET')return dashboard(env,url);
  if(url.pathname==='/api/options'&&m==='GET')return listOptions(env);
  if(url.pathname==='/api/options'&&m==='POST'){admin(user);return addOption(req,env,user);}
  if(url.pathname.startsWith('/api/options/')&&m==='DELETE'){admin(user);return deleteOption(url,env,user);}

  if(url.pathname==='/api/masters/resolve'&&m==='POST')return resolveMasters(req,env);
  if(url.pathname==='/api/master/stores'&&m==='POST'){admin(user);return saveStores(req,env,user);}
  if(url.pathname==='/api/master/stores/status'&&m==='GET')return storeStatus(env);
  if(url.pathname==='/api/master-article/status'&&m==='GET')return masterStatus(env);
  if(url.pathname==='/api/master-article/start'&&m==='POST'){admin(user);return masterStart(req,env,user);}
  if(url.pathname==='/api/master-article/chunk'&&m==='POST'){admin(user);return masterChunk(req,env);}
  if(url.pathname==='/api/master-article/finalize'&&m==='POST'){admin(user);return masterFinalize(req,env,user);}
  if(url.pathname==='/api/master-article/abort'&&m==='POST'){admin(user);return masterAbort(req,env,user);}

  if(url.pathname==='/api/claims'&&m==='GET')return listClaims(env,url);
  if(url.pathname==='/api/claims/prepare'&&m==='POST')return prepareClaims(req,env);
  if(url.pathname==='/api/claims/save'&&m==='POST')return saveClaims(req,env,user);
  if(url.pathname==='/api/claims/export'&&m==='GET')return exportClaims(env,url);
  if(url.pathname.startsWith('/api/claims/case/')&&m==='GET')return getCase(env,url);
  if(url.pathname.startsWith('/api/claims/case/')&&m==='DELETE'){admin(user);return deleteCase(env,url,user);}

  if(url.pathname==='/api/validation/run'&&m==='POST')return runValidation(req,env);
  if(url.pathname==='/api/references'&&m==='GET')return listRefs(env,url);
  if(url.pathname==='/api/performance'&&m==='GET')return performance(env,url);
  if(url.pathname==='/api/audit'&&m==='GET'){supervisor(user);return auditList(env,url);}

  if(url.pathname==='/api/users'&&m==='GET'){admin(user);return listUsers(env);}
  if(url.pathname==='/api/users'&&m==='POST'){admin(user);return createUser(req,env,user);}
  if(url.pathname.startsWith('/api/users/')&&url.pathname.endsWith('/password')&&m==='POST'){admin(user);return resetUserPassword(req,env,url,user);}
  if(url.pathname.startsWith('/api/users/')&&url.pathname.endsWith('/status')&&m==='POST'){admin(user);return setUserStatus(req,env,url,user);}
  if(url.pathname.startsWith('/api/users/')&&m==='DELETE'){admin(user);return deleteUser(env,url,user);}
  if(url.pathname==='/api/profile'&&m==='POST')return updateProfile(req,env,user);
  if(url.pathname==='/api/profile/password'&&m==='POST')return changePassword(req,env,user);

  return json({status:'error',message:'API not found'},404);
}

async function ensureAdmin(env){
  const n=await env.DB.prepare('SELECT COUNT(*) n FROM users').first();if(Number(n?.n||0)>0)return;
  const username=text(env.ADMIN_USERNAME);
  if(!username)throw pub(503,'ยังไม่ได้ตั้ง ADMIN_USERNAME เป็น Cloudflare secret');
  if(!env.ADMIN_PASSWORD)throw pub(503,'ยังไม่ได้ตั้ง ADMIN_PASSWORD');
  const t=now();await env.DB.prepare("INSERT INTO users(username,password_hash,display_name,role,active,created_at,updated_at) VALUES(?,?,?,'admin',1,?,?)").bind(username,hashPassword(env.ADMIN_PASSWORD),'Administrator',t,t).run();
}
async function login(req,env,url){
  await ensureAdmin(env);
  const b=await body(req),username=text(b.username),rateKey=loginRateKey(req,username),limit=await loginRateState(env,rateKey);
  if(limit.blocked)return json({status:'error',message:'ลองเข้าสู่ระบบหลายครั้งเกินไป กรุณารอสักครู่แล้วลองใหม่',retryAfter:limit.retryAfter},429);
  const u=await env.DB.prepare('SELECT * FROM users WHERE username=? COLLATE NOCASE').bind(username).first();
  if(!u||!u.active||!verifyPassword(b.password,u.password_hash)){
    await recordLoginFailure(env,rateKey);
    return json({status:'error',message:'ชื่อผู้ใช้งานหรือรหัสผ่านไม่ถูกต้อง'},401);
  }
  await clearLoginFailures(env,rateKey);
  const token=randomBytes(32).toString('base64url'),h=sha(token),age=Math.max(1,Number(env.SESSION_HOURS||10))*3600,ts=Date.now();
  await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires_at<=?').bind(ts),env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,?)').bind(h,u.id,ts+age*1000,ts,ts),env.DB.prepare('UPDATE users SET last_login_at=?,updated_at=? WHERE id=?').bind(now(),now(),u.id)]);
  await log(env,u.username,'LOGIN','USER',String(u.id),'','','','Login success');
  const r=json({status:'success',user:publicUser(u)});r.headers.append('Set-Cookie',cookie(token,age,url.protocol==='https:'));return r;
}
async function logout(req,env,url){const token=getCookie(req);if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(sha(token)).run();const r=json({status:'success'});r.headers.append('Set-Cookie',cookie('',0,url.protocol==='https:'));return r;}

const LOGIN_WINDOW_MS=15*60*1000,LOGIN_BLOCK_MS=15*60*1000,LOGIN_MAX_FAILURES=8;
function loginRateKey(req,username){const ip=text(req.headers.get('CF-Connecting-IP')||req.headers.get('x-forwarded-for')||'unknown');return sha(`${ip}|${String(username||'').toLowerCase()}`);}
async function loginRateState(env,key){const t=Date.now(),r=await env.DB.prepare('SELECT failures,window_started_at,blocked_until FROM login_rate_limits WHERE rate_key=?').bind(key).first();if(!r)return{blocked:false,retryAfter:0};if(Number(r.blocked_until||0)>t)return{blocked:true,retryAfter:Math.ceil((Number(r.blocked_until)-t)/1000)};if(t-Number(r.window_started_at||0)>LOGIN_WINDOW_MS){await env.DB.prepare('DELETE FROM login_rate_limits WHERE rate_key=?').bind(key).run();return{blocked:false,retryAfter:0};}return{blocked:false,retryAfter:0};}
async function recordLoginFailure(env,key){const t=Date.now(),r=await env.DB.prepare('SELECT failures,window_started_at FROM login_rate_limits WHERE rate_key=?').bind(key).first();let started=t,failures=1;if(r&&t-Number(r.window_started_at||0)<=LOGIN_WINDOW_MS){started=Number(r.window_started_at);failures=Number(r.failures||0)+1;}const blocked=failures>=LOGIN_MAX_FAILURES?t+LOGIN_BLOCK_MS:0;await env.DB.prepare('INSERT INTO login_rate_limits(rate_key,failures,window_started_at,blocked_until,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(rate_key) DO UPDATE SET failures=excluded.failures,window_started_at=excluded.window_started_at,blocked_until=excluded.blocked_until,updated_at=excluded.updated_at').bind(key,failures,started,blocked,t).run();}
async function clearLoginFailures(env,key){await env.DB.prepare('DELETE FROM login_rate_limits WHERE rate_key=?').bind(key).run();}

async function requireUser(req,env){const t=getCookie(req);if(!t)throw pub(401,'กรุณาเข้าสู่ระบบ');const r=await env.DB.prepare('SELECT u.*,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(sha(t),Date.now()).first();if(!r)throw pub(401,'Session หมดอายุ กรุณาเข้าสู่ระบบใหม่');return r;}
function publicUser(u){return{id:u.id,username:u.username,displayName:u.display_name||u.username,role:u.role,active:Boolean(u.active),lastLoginAt:u.last_login_at||''};}
function admin(u){if(u.role!=='admin')throw pub(403,'Administrator only');}
function supervisor(u){if(!['admin','supervisor'].includes(u.role))throw pub(403,'Supervisor or Administrator only');}
async function listUsers(env){const r=await env.DB.prepare('SELECT id,username,display_name,role,active,last_login_at,created_at FROM users ORDER BY active DESC,username').all();return json({status:'success',data:r.results||[]});}
async function createUser(req,env,actor){const b=await body(req),username=text(b.username),display=text(b.displayName),role=['admin','supervisor','user'].includes(b.role)?b.role:'user';if(!username)return json({status:'error',message:'กรุณาระบุ Username'},422);if(!strong(b.password))return json({status:'error',message:'รหัสผ่านอย่างน้อย 10 ตัว มีตัวอักษรและตัวเลข'},422);const t=now();try{await env.DB.prepare('INSERT INTO users(username,password_hash,display_name,role,active,created_at,updated_at) VALUES(?,?,?,?,1,?,?)').bind(username,hashPassword(b.password),display,role,t,t).run();}catch(e){if(String(e.message).includes('UNIQUE'))return json({status:'error',message:'Username นี้มีอยู่แล้ว'},409);throw e;}await log(env,actor.username,'CREATE_USER','USER',username,'','','',`role=${role}`);return json({status:'success'},201);}
async function resetUserPassword(req,env,url,actor){const id=Number(url.pathname.split('/').at(-2)),b=await body(req);if(!strong(b.password))return json({status:'error',message:'รหัสผ่านอย่างน้อย 10 ตัว มีตัวอักษรและตัวเลข'},422);await env.DB.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').bind(hashPassword(b.password),now(),id).run();await log(env,actor.username,'RESET_PASSWORD','USER',String(id));return json({status:'success'});}
async function setUserStatus(req,env,url,actor){const id=Number(url.pathname.split('/').at(-2)),b=await body(req);if(id===actor.id&&!b.active)return json({status:'error',message:'ปิดบัญชีที่กำลังใช้งานไม่ได้'},422);await env.DB.prepare('UPDATE users SET active=?,updated_at=? WHERE id=?').bind(b.active?1:0,now(),id).run();await log(env,actor.username,'USER_STATUS','USER',String(id),'','','',`active=${Boolean(b.active)}`);return json({status:'success'});}
async function deleteUser(env,url,actor){const id=Number(url.pathname.split('/').pop());if(id===actor.id)return json({status:'error',message:'ลบบัญชีที่กำลังใช้งานไม่ได้'},422);await env.DB.prepare('DELETE FROM users WHERE id=?').bind(id).run();await log(env,actor.username,'DELETE_USER','USER',String(id));return json({status:'success'});}
async function updateProfile(req,env,user){const b=await body(req),d=text(b.displayName);await env.DB.prepare('UPDATE users SET display_name=?,updated_at=? WHERE id=?').bind(d,now(),user.id).run();return json({status:'success',user:{...publicUser(user),displayName:d||user.username}});}
async function changePassword(req,env,user){const b=await body(req);if(!strong(b.password))return json({status:'error',message:'รหัสผ่านอย่างน้อย 10 ตัว มีตัวอักษรและตัวเลข'},422);await env.DB.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').bind(hashPassword(b.password),now(),user.id).run();await log(env,user.username,'CHANGE_PASSWORD','USER',String(user.id));return json({status:'success'});}

async function listOptions(env){const r=await env.DB.prepare('SELECT id,category,value,sort_order FROM dropdown_options WHERE active=1 ORDER BY category,sort_order,id').all(),g={};for(const x of r.results||[])(g[x.category]||=[]).push(x);return json({status:'success',data:g});}
async function addOption(req,env,user){const b=await body(req),c=text(b.category),v=text(b.value);if(!CATS.has(c)||!v)return json({status:'error',message:'Dropdown ไม่ถูกต้อง'},422);const mx=await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0) n FROM dropdown_options WHERE category=?').bind(c).first();await env.DB.prepare('INSERT INTO dropdown_options(category,value,sort_order,active,created_by,created_at) VALUES(?,?,?,1,?,?) ON CONFLICT(category,value) DO UPDATE SET active=1').bind(c,v,Number(mx?.n||0)+10,user.username,now()).run();await log(env,user.username,'ADD_OPTION','OPTION',`${c}:${v}`);return listOptions(env);}
async function deleteOption(url,env,user){const id=Number(url.pathname.split('/').pop());await env.DB.prepare('UPDATE dropdown_options SET active=0 WHERE id=?').bind(id).run();await log(env,user.username,'REMOVE_OPTION','OPTION',String(id));return listOptions(env);}

async function resolveMasters(req,env){const b=await body(req),stores=uniq((b.stores||[]).map(digits).filter(Boolean)).slice(0,100),keys=uniq((b.articles||[]).map(x=>text(x).replaceAll("'",'')).filter(Boolean)).slice(0,80),data={stores:{},products:{}};if(stores.length){const r=await env.DB.prepare(`SELECT * FROM master_stores WHERE store_code IN (${marks(stores.length)})`).bind(...stores).all();for(const x of r.results||[])data.stores[x.store_code]=x;}if(keys.length){const active=await env.DB.prepare('SELECT active_batch_id FROM master_article_state WHERE id=1').first();if(active?.active_batch_id){const r=await env.DB.prepare(`SELECT * FROM master_articles WHERE batch_id=? AND (article IN (${marks(keys.length)}) OR barcode IN (${marks(keys.length)}))`).bind(active.active_batch_id,...keys,...keys).all();for(const x of r.results||[]){if(x.article)data.products[x.article]=x;if(x.barcode)data.products[x.barcode]=x;}}}return json({status:'success',data});}
async function saveStores(req,env,user){const b=await body(req,8*1024*1024),rows=Array.isArray(b.records)?b.records:[];if(rows.length>1000)return json({status:'error',message:'ครั้งละไม่เกิน 1,000 สาขา'},413);let count=0;const t=now();for(let i=0;i<rows.length;i+=40){const st=[];for(const raw of rows.slice(i,i+40)){const r=Array.isArray(raw)?{code:digits(raw[0]),name:text(raw[1]||raw[4]),format:text(raw[20]),type:text(raw[21]),check:text(raw[22]||'')}:{code:digits(raw.storeCode),name:text(raw.storeName),format:text(raw.formatType),type:text(raw.storeType),check:text(raw.check100)};if(!r.code)continue;st.push(env.DB.prepare('INSERT INTO master_stores(store_code,store_name,format_type,store_type,check_100,raw_json,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(store_code) DO UPDATE SET store_name=excluded.store_name,format_type=excluded.format_type,store_type=excluded.store_type,check_100=excluded.check_100,raw_json=excluded.raw_json,updated_at=excluded.updated_at').bind(r.code,r.name,r.format,r.type,r.check,JSON.stringify(raw),t));count++;}if(st.length)await env.DB.batch(st);}await log(env,user.username,'UPLOAD_MASTER_STORE','MASTER','MasterStore','','','','rows='+count);return json({status:'success',count});}
async function storeStatus(env){const r=await env.DB.prepare('SELECT COUNT(*) n,MAX(updated_at) updated_at FROM master_stores').first();return json({status:'success',data:{count:Number(r?.n||0),updatedAt:r?.updated_at||''}});}
async function masterStatus(env){const r=await env.DB.prepare('SELECT b.*,(SELECT COUNT(*) FROM master_articles a WHERE a.batch_id=b.batch_id) article_count FROM master_article_state s LEFT JOIN master_article_batches b ON b.batch_id=s.active_batch_id WHERE s.id=1').first();return json({status:'success',data:r?.batch_id?{active:true,batchId:r.batch_id,sourceFile:r.source_file,expectedRows:Number(r.expected_rows||0),receivedRows:Number(r.received_rows||0),articleCount:Number(r.article_count||0),activatedAt:r.activated_at}:{active:false,articleCount:0}});}
async function masterStart(req,env,user){const b=await body(req),headers=b.headers||[],n=Number(b.totalRows||0);if(text(headers[0]).toUpperCase()!=='ARTICLE'||text(headers[35]).toUpperCase()!=='ITEM_VALUE')return json({status:'error',message:'MasterArticle: A ต้องเป็น ARTICLE และ AJ ต้องเป็น ITEM_VALUE'},422);const id=`MA-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;await env.DB.prepare("INSERT INTO master_article_batches(batch_id,source_file,sheet_name,expected_rows,received_rows,status,created_by,created_at,activated_at) VALUES(?,?,?,?,0,'uploading',?,?, '')").bind(id,text(b.fileName),text(b.sheetName),n,user.username,now()).run();return json({status:'success',batchId:id,chunkLimit:50},201);}
async function masterChunk(req,env){const b=await body(req,3*1024*1024),id=text(b.batchId),rows=Array.isArray(b.rows)?b.rows:[];if(!id||!rows.length||rows.length>50)return json({status:'error',message:'MasterArticle chunk 1-50 rows'},422);const st=[];for(const raw of rows){if(!Array.isArray(raw)||raw.length<40)continue;const a=text(raw[0]).replaceAll("'",'');if(!a)continue;st.push(env.DB.prepare('INSERT OR REPLACE INTO master_articles(batch_id,article,barcode,description,manage_weight,item_value,seg_description,eggs,raw_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,a,text(raw[3]).replaceAll("'",''),text(raw[4]),text(raw[11]),num(raw[35]),text(raw[39]),text(raw[40]||''),JSON.stringify(raw),now()));}st.push(env.DB.prepare('UPDATE master_article_batches SET received_rows=received_rows+? WHERE batch_id=?').bind(rows.length,id));await env.DB.batch(st);const p=await env.DB.prepare('SELECT received_rows,expected_rows FROM master_article_batches WHERE batch_id=?').bind(id).first();return json({status:'success',receivedRows:Number(p?.received_rows||0),expectedRows:Number(p?.expected_rows||0)});}
async function masterFinalize(req,env,user){const b=await body(req),id=text(b.batchId),x=await env.DB.prepare("SELECT * FROM master_article_batches WHERE batch_id=? AND status='uploading'").bind(id).first();if(!x)return json({status:'error',message:'Batch not found'},404);if(Number(x.received_rows)!==Number(x.expected_rows))return json({status:'error',message:`อัปโหลดไม่ครบ ${x.received_rows}/${x.expected_rows}`},422);const old=await env.DB.prepare('SELECT active_batch_id FROM master_article_state WHERE id=1').first(),t=now();await env.DB.batch([env.DB.prepare("UPDATE master_article_batches SET status='replaced' WHERE status='active'"),env.DB.prepare("UPDATE master_article_batches SET status='active',activated_at=? WHERE batch_id=?").bind(t,id),env.DB.prepare('UPDATE master_article_state SET active_batch_id=?,updated_at=? WHERE id=1').bind(id,t)]);if(old?.active_batch_id&&old.active_batch_id!==id){await env.DB.prepare('DELETE FROM master_articles WHERE batch_id=?').bind(old.active_batch_id).run();await env.DB.prepare('DELETE FROM master_article_batches WHERE batch_id=?').bind(old.active_batch_id).run();}await log(env,user.username,'REPLACE_MASTER_ARTICLE','MASTER',id,'','','',`rows=${x.expected_rows}`);return masterStatus(env);}
async function masterAbort(req,env,user){const b=await body(req),id=text(b.batchId);await env.DB.prepare('DELETE FROM master_article_batches WHERE batch_id=?').bind(id).run();await log(env,user.username,'ABORT_MASTER_ARTICLE','MASTER',id);return json({status:'success'});}

async function prepareClaims(req,env){const b=await body(req,2*1024*1024),rows=(Array.isArray(b.rows)?b.rows:[]).map(normalizeRaw);if(!rows.length)return json({status:'error',message:'ไม่พบข้อมูล'},422);const stores=uniq(rows.map(x=>x.storeCode)),keys=uniq(rows.flatMap(x=>[x.article,x.barcode]).filter(Boolean)),resolved=await resolveMasterData(env,stores,keys);for(const r of rows)enrich(r,resolved);const first=rows[0]||{};const dup=first.transportNo?await env.DB.prepare('SELECT claim_no,reference_no,update_status,who,ship_date FROM claims WHERE archived=0 AND transport_no=? ORDER BY id DESC LIMIT 5').bind(first.transportNo).all():{results:[]};return json({status:'success',rows,summary:summarize(rows),duplicateCases:dup.results||[]});}
async function saveClaims(req,env,user){const b=await body(req,3*1024*1024),source=Array.isArray(b.rows)?b.rows:[];if(!source.length)return json({status:'error',message:'ไม่พบข้อมูล'},422);if(source.length>100)return json({status:'error',message:'บันทึกครั้งละไม่เกิน 100 แถว'},413);const rows=source.map(normalizeRaw),stores=uniq(rows.map(x=>x.storeCode)),keys=uniq(rows.flatMap(x=>[x.article,x.barcode]).filter(Boolean)),resolved=await resolveMasterData(env,stores,keys);for(const r of rows)enrich(r,resolved);const meta=normalizeMeta(b.meta||{}),errs=validateBatch(rows,meta);if(errs.length)return json({status:'error',message:'ข้อมูลไม่ผ่าน Validation',details:errs},422);const transport=rows[0].transportNo;if(!b.editClaimNo){const d=await env.DB.prepare('SELECT claim_no FROM claims WHERE archived=0 AND transport_no=? LIMIT 1').bind(transport).first();if(d&&!b.confirmDuplicate)return json({status:'duplicate',message:'Transport No. นี้มีข้อมูลอยู่แล้ว',requiresConfirmation:true,transportNo:transport},409);}
  const ship=meta.shipDate||today(),ym=ship.slice(0,7).replace('-',''),claimNo=b.editClaimNo||await nextClaim(env,ym),refNo=meta.status==='Accept'&&['DC','TP'].includes(meta.who)?(b.editReferenceNo||await nextRef(env,meta.who)):'',t=now();
  if(b.editClaimNo){await env.DB.prepare('UPDATE claims SET archived=1,updated_at=?,updated_by=? WHERE claim_no=?').bind(t,user.username,b.editClaimNo).run();}
  const stmts=[];let n=0;for(const r of rows){const key=`${Date.now()}_${String(n+1).padStart(3,'0')}_${crypto.randomUUID().slice(0,6)}`,month=new Intl.DateTimeFormat('en',{month:'short',timeZone:'Asia/Bangkok'}).format(new Date(ship+'T00:00:00+07:00')),year=Number(ship.slice(0,4));const v=[r.storeCode,r.storeName,r.claimDc,r.receivedDate,r.claimDate,r.transportNo,r.vehicleNo,r.driver,r.dnNo,r.route,r.palletNo,r.basketNo,r.article,r.barcode,r.description,r.deliveryQty,r.receivedQty,r.claimQty,meta.reason,r.amount,ship,meta.status,meta.who,r.formatType,claimNo,refNo,meta.causeGroup,meta.rootCause,meta.checkResult,meta.remarkList,r.eggs,r.storeFormat,r.manageWeight,meta.sc,meta.completeSc,meta.remark,r.storeCheck100,r.skuCost,r.segDescription,user.username,key,month,year,0,t,t,user.username];stmts.push(env.DB.prepare(`INSERT INTO claims(store_code,store_name,claim_dc,received_date,claim_date,transport_no,vehicle_no,driver,dn_no,route,pallet_no,basket_no,article,barcode,description,delivery_qty,received_qty,claim_qty,claims_reason,amount_claim,ship_date,update_status,who,format_type,claim_no,reference_no,cause_group,root_cause,check_result,remark_list,eggs,store_format,manage_weight,sc,complete_sc,remark,store_check_100,sku_cost,seg_description,created_by,unique_key,data_month,data_year,archived,created_at,updated_at,updated_by) VALUES(${marks(v.length)})`).bind(...v));n++;}
  for(let i=0;i<stmts.length;i+=25)await env.DB.batch(stmts.slice(i,i+25));if(refNo){await env.DB.prepare('INSERT OR IGNORE INTO references_ledger(ref_type,ref_no,claim_no,transport_no,store_code,ship_date,remark,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(meta.who,refNo,claimNo,transport,rows[0].storeCode,ship,meta.remark,user.username,t).run();}await log(env,user.username,b.editClaimNo?'EDIT_CLAIM':'CREATE_CLAIM','CLAIM',claimNo,claimNo,refNo,transport,`${rows.length} rows · ${meta.status}/${meta.who}`);return json({status:'success',count:rows.length,claimNo,referenceNo:refNo,totalAmount:summarize(rows).totalAmount});}
async function listClaims(env,url){const q=[],p=[];for(const [k,c] of [['transport','transport_no'],['reference','reference_no'],['claim','claim_no'],['store','store_code'],['article','article'],['date','ship_date'],['status','update_status'],['who','who']]){const v=text(url.searchParams.get(k));if(v){q.push(`${c}=?`);p.push(v);}}q.push('archived=0');const lim=Math.min(500,Math.max(50,Number(url.searchParams.get('limit')||200)));const r=await env.DB.prepare(`SELECT * FROM claims WHERE ${q.join(' AND ')} ORDER BY id DESC LIMIT ?`).bind(...p,lim).all();const groups=group(r.results||[]);return json({status:'success',groups,totalGroups:groups.length});}
function group(rows){const m=new Map();for(const r of rows){const k=r.claim_no||`${r.transport_no}|${r.ship_date}|${r.update_status}|${r.who}`;if(!m.has(k))m.set(k,{key:k,claimNo:r.claim_no,referenceNo:r.reference_no,transportNo:r.transport_no,shipDate:r.ship_date,status:r.update_status,who:r.who,storeCode:r.store_code,storeName:r.store_name,formatType:r.format_type,totalAmount:0,rows:[]});const g=m.get(k);g.totalAmount=roundMoney(g.totalAmount+Number(r.amount_claim||0));g.rows.push(apiRow(r));}return[...m.values()];}
async function getCase(env,url){const claim=decodeURIComponent(url.pathname.split('/').pop());const r=await env.DB.prepare('SELECT * FROM claims WHERE archived=0 AND claim_no=? ORDER BY id').bind(claim).all();if(!(r.results||[]).length)return json({status:'error',message:'ไม่พบ Claim'},404);return json({status:'success',rows:r.results.map(apiRow)});}
async function deleteCase(env,url,user){const claim=decodeURIComponent(url.pathname.split('/').pop());const rows=await env.DB.prepare('SELECT transport_no,reference_no FROM claims WHERE claim_no=? AND archived=0 LIMIT 1').bind(claim).first();await env.DB.prepare('UPDATE claims SET archived=1,updated_at=?,updated_by=? WHERE claim_no=?').bind(now(),user.username,claim).run();await log(env,user.username,'DELETE_CLAIM','CLAIM',claim,claim,rows?.reference_no||'',rows?.transport_no||'');return json({status:'success'});}
async function exportClaims(env,url){const q=['archived=0'],p=[];const y=text(url.searchParams.get('year')),m=text(url.searchParams.get('month'));if(y){q.push('data_year=?');p.push(Number(y));}if(m){q.push('data_month=?');p.push(m);}const r=await env.DB.prepare(`SELECT * FROM claims WHERE ${q.join(' AND ')} ORDER BY id`).bind(...p).all();return json({status:'success',headers:HEADERS,rows:(r.results||[]).map(exportRow)});}
async function runValidation(req,env){const b=await body(req,2*1024*1024),rows=Array.isArray(b.rows)?b.rows:[];if(rows.length>1000)return json({status:'error',message:'ครั้งละไม่เกิน 1,000 แถว'},413);const out=[];for(let i=0;i<rows.length;i+=50){const c=rows.slice(i,i+50),conds=[],p=[];for(const x of c){conds.push('(store_code=? AND article=? AND reference_no=?)');p.push(digits(x.storeCode),text(x.article).replaceAll("'",''),text(x.referenceNo));}const r=conds.length?await env.DB.prepare(`SELECT store_code,article,reference_no,transport_no,vehicle_no,driver,ship_date,claim_no,check_result,who FROM claims WHERE archived=0 AND (${conds.join(' OR ')})`).bind(...p).all():{results:[]},map=new Map((r.results||[]).map(x=>[`${x.store_code}|${x.article}|${x.reference_no}`,x]));for(const x of c){const key=`${digits(x.storeCode)}|${text(x.article).replaceAll("'",'')}|${text(x.referenceNo)}`,hit=map.get(key);out.push({...x,valid:Boolean(hit),result:hit?'Valid':'No Valid',whoAccept:hit?.check_result||'No Accept',remark:hit?'Process ในระบบได้':'เลข Reference ไม่สามารถตรวจสอบได้ / ไม่สอดคล้องกับรายการเคลม',transportNo:hit?.transport_no||'-',vehicleNo:hit?.vehicle_no||'-',driver:hit?.driver||'-',claimDate:hit?.ship_date||'-',claimNo:hit?.claim_no||'-'});}}return json({status:'success',data:out,valid:out.filter(x=>x.valid).length,invalid:out.filter(x=>!x.valid).length});}

async function dashboard(env,url){const y=Number(url.searchParams.get('year')||new Date().getFullYear()),m=text(url.searchParams.get('month')),where=['archived=0','data_year=?'],p=[y];if(m&&m!=='all'){where.push('data_month=?');p.push(m);}const w=where.join(' AND ');const s=await env.DB.prepare(`SELECT COUNT(DISTINCT claim_no) cases,COALESCE(SUM(amount_claim),0) amount,COUNT(*) lines,COUNT(DISTINCT store_code) stores,COUNT(DISTINCT transport_no) transports FROM claims WHERE ${w}`).bind(...p).first();const st=await env.DB.prepare(`SELECT update_status name,COUNT(DISTINCT claim_no) value FROM claims WHERE ${w} GROUP BY update_status ORDER BY value DESC`).bind(...p).all();const who=await env.DB.prepare(`SELECT who name,COUNT(DISTINCT claim_no) value FROM claims WHERE ${w} GROUP BY who ORDER BY value DESC`).bind(...p).all();const trend=await env.DB.prepare(`SELECT ship_date date,COUNT(DISTINCT claim_no) cases,COALESCE(SUM(amount_claim),0) amount FROM claims WHERE ${w} GROUP BY ship_date ORDER BY ship_date`).bind(...p).all();const recent=await env.DB.prepare(`SELECT claim_no,reference_no,transport_no,ship_date,update_status,who,store_code,store_name,SUM(amount_claim) amount FROM claims WHERE ${w} GROUP BY claim_no ORDER BY MAX(id) DESC LIMIT 10`).bind(...p).all();return json({status:'success',data:{summary:{cases:Number(s?.cases||0),amount:Number(s?.amount||0),lines:Number(s?.lines||0),stores:Number(s?.stores||0),transports:Number(s?.transports||0)},status:st.results||[],who:who.results||[],trend:trend.results||[],recent:recent.results||[]}});}
async function listRefs(env,url){const type=text(url.searchParams.get('type'));const r=await env.DB.prepare(`SELECT * FROM references_ledger ${type?'WHERE ref_type=?':''} ORDER BY id DESC LIMIT 500`).bind(...(type?[type]:[])).all();return json({status:'success',data:r.results||[]});}
async function performance(env,url){const date=text(url.searchParams.get('date'))||today();const r=await env.DB.prepare(`SELECT created_by username,COUNT(DISTINCT claim_no) cases,COUNT(*) lines,COALESCE(SUM(amount_claim),0) amount FROM claims WHERE archived=0 AND ship_date=? GROUP BY created_by ORDER BY cases DESC`).bind(date).all();return json({status:'success',data:r.results||[]});}
async function auditList(env,url){const lim=Math.min(500,Math.max(50,Number(url.searchParams.get('limit')||200))),u=text(url.searchParams.get('user')),a=text(url.searchParams.get('action')),q=[],p=[];if(u){q.push('username=?');p.push(u);}if(a){q.push('action=?');p.push(a);}const r=await env.DB.prepare(`SELECT * FROM audit_log ${q.length?'WHERE '+q.join(' AND '):''} ORDER BY id DESC LIMIT ?`).bind(...p,lim).all();return json({status:'success',data:r.results||[]});}

async function resolveMasterData(env,stores,keys){const out={stores:new Map(),products:new Map()};if(stores.length){const r=await env.DB.prepare(`SELECT * FROM master_stores WHERE store_code IN (${marks(stores.length)})`).bind(...stores).all();for(const x of r.results||[])out.stores.set(x.store_code,x);}const active=await env.DB.prepare('SELECT active_batch_id FROM master_article_state WHERE id=1').first();if(keys.length&&active?.active_batch_id){const r=await env.DB.prepare(`SELECT * FROM master_articles WHERE batch_id=? AND (article IN (${marks(keys.length)}) OR barcode IN (${marks(keys.length)}))`).bind(active.active_batch_id,...keys,...keys).all();for(const x of r.results||[]){if(x.article)out.products.set(x.article,x);if(x.barcode)out.products.set(x.barcode,x);}}return out;}
function normalizeRaw(x){return{storeCode:digits(x.storeCode),storeName:text(x.storeName),claimDc:text(x.claimDc)||'92924 - DC อาหารสด ฉะเชิงเทรา',receivedDate:dateIso(x.receivedDate),claimDate:dateIso(x.claimDate||x.reportedDate),transportNo:text(x.transportNo),vehicleNo:text(x.vehicleNo),driver:text(x.driver),dnNo:text(x.dnNo),route:text(x.route),palletNo:text(x.palletNo).replace(/^'/,''),basketNo:text(x.basketNo),article:text(x.article).replaceAll("'",''),barcode:text(x.barcode).replaceAll("'",''),description:text(x.description),deliveryQty:numericText(x.deliveryQty??x.sentQty),receivedQty:numericText(x.receivedQty),claimQty:numericText(x.claimQty),amount:num(x.amount),skuCost:num(x.skuCost),formatType:text(x.formatType),storeFormat:text(x.storeFormat),manageWeight:text(x.manageWeight),eggs:text(x.eggs),storeCheck100:text(x.storeCheck100),segDescription:text(x.segDescription)};}
function enrich(r,res){const s=res.stores.get(r.storeCode)||{},p=res.products.get(r.article)||res.products.get(r.barcode)||{};r.storeName=r.storeName||text(s.store_name);r.formatType=formatType(r.storeCode,text(s.format_type));r.storeFormat=text(s.store_type)||r.storeFormat;r.storeCheck100=text(s.check_100)||r.storeCheck100;if(p.article)r.article=text(p.article);if(!r.barcode&&p.barcode)r.barcode=text(p.barcode);r.description=r.description||text(p.description);r.manageWeight=text(p.manage_weight)||r.manageWeight;r.skuCost=Number(p.item_value??r.skuCost??0);r.segDescription=text(p.seg_description)||r.segDescription;r.eggs=text(p.eggs)||r.eggs;r.amount=roundMoney(r.skuCost*num(r.claimQty));}
function normalizeMeta(m){return{reason:text(m.reason),shipDate:dateIso(m.shipDate)||today(),status:text(m.status),who:text(m.who),causeGroup:text(m.causeGroup),rootCause:text(m.rootCause),checkResult:text(m.checkResult),remarkList:text(m.remarkList),sc:text(m.sc),completeSc:text(m.completeSc),remark:text(m.remark)};}
function validateBatch(rows,m){const e=[];if(!m.shipDate)e.push('Ship Date ห้ามว่าง');if(!['Accept','Pending','Reject'].includes(m.status))e.push('Update status ไม่ถูกต้อง');if(!['DC','TP','QC'].includes(m.who))e.push('WHO ไม่ถูกต้อง');if(!m.reason)e.push('Claims Reason ห้ามว่าง');if(!m.rootCause)e.push('ROOT CAUSE ห้ามว่าง');for(const [i,r] of rows.entries()){if(!r.storeCode)e.push(`แถว ${i+1}: Store Code ห้ามว่าง`);if(!r.transportNo)e.push(`แถว ${i+1}: Transport No. ห้ามว่าง`);if(!r.article)e.push(`แถว ${i+1}: Article ห้ามว่าง`);if(!Number.isFinite(r.amount))e.push(`แถว ${i+1}: Amount ไม่ถูกต้อง`);}return e.slice(0,30);}
function summarize(rows){return{rows:rows.length,totalAmount:roundMoney(rows.reduce((s,x)=>s+num(x.amount),0)),transportNo:rows[0]?.transportNo||'',storeCode:rows[0]?.storeCode||'',formatType:rows[0]?.formatType||'',missingPrice:rows.filter(x=>!num(x.skuCost)).length};}
async function nextClaim(env,ym){const n=await reserve(env,`CLAIM:${ym}`);return`CM-${ym}${String(n).padStart(6,'0')}`;}
async function nextRef(env,who){const p=who==='DC'?'CCD':'TF',n=await reserve(env,`REF:${p}`);return`${p}${String(n).padStart(7,'0')}`;}
async function reserve(env,k){const r=await env.DB.prepare('INSERT INTO sequences(sequence_key,current_value) VALUES(?,1) ON CONFLICT(sequence_key) DO UPDATE SET current_value=current_value+1 RETURNING current_value').bind(k).first();return Number(r?.current_value||1);}
function apiRow(r){return{storeCode:r.store_code,storeName:r.store_name,claimDc:r.claim_dc,receivedDate:r.received_date,claimDate:r.claim_date,transportNo:r.transport_no,vehicleNo:r.vehicle_no,driver:r.driver,dnNo:r.dn_no,route:r.route,palletNo:r.pallet_no,basketNo:r.basket_no,article:r.article,barcode:r.barcode,description:r.description,deliveryQty:r.delivery_qty,receivedQty:r.received_qty,claimQty:r.claim_qty,reason:r.claims_reason,amount:roundMoney(r.amount_claim),shipDate:r.ship_date,status:r.update_status,who:r.who,formatType:r.format_type,claimNo:r.claim_no,referenceNo:r.reference_no,causeGroup:r.cause_group,rootCause:r.root_cause,checkResult:r.check_result,remarkList:r.remark_list,eggs:r.eggs,storeFormat:r.store_format,manageWeight:r.manage_weight,sc:r.sc,completeSc:r.complete_sc,remark:r.remark,storeCheck100:r.store_check_100,skuCost:Number(r.sku_cost||0),segDescription:r.seg_description,createdBy:r.created_by,uniqueKey:r.unique_key,month:r.data_month,year:r.data_year};}
function exportRow(r){return[r.store_code,r.store_name,r.claim_dc,r.received_date,r.claim_date,r.transport_no,r.vehicle_no,r.driver,r.dn_no,r.route,r.pallet_no,r.basket_no,r.article,r.barcode,r.description,r.delivery_qty,r.received_qty,r.claim_qty,r.claims_reason,roundMoney(r.amount_claim),r.ship_date,r.update_status,r.who,r.format_type,r.claim_no,r.reference_no,r.cause_group,r.root_cause,r.check_result,r.remark_list,r.eggs,r.store_format,r.manage_weight,r.sc,r.complete_sc,r.remark,r.store_check_100,Number(r.sku_cost||0),r.seg_description,r.created_by,r.unique_key,r.data_month,r.data_year];}
function formatType(code,master){if(master)return master;const c=String(code||'')[0];return c==='1'?'HYPER':c==='2'?'MBC':c==='3'?'Franchise':'';}
async function log(env,username,action,type,key,claim='',ref='',transport='',details=''){await env.DB.prepare('INSERT INTO audit_log(username,action,entity_type,entity_key,claim_no,reference_no,transport_no,details,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(username,action,type,key,claim,ref,transport,details,now()).run();}
async function body(req,max=1024*1024){const len=Number(req.headers.get('content-length')||0);if(len>max)throw pub(413,'Payload too large');try{return await req.json();}catch{throw pub(400,'JSON ไม่ถูกต้อง');}}
function pub(status,msg){const e=new Error(msg);e.status=status;e.publicMessage=msg;return e;}
function text(v){return String(v??'').trim();}function roundMoney(v){return Math.round((num(v)+Number.EPSILON)*100)/100;}function digits(v){const s=text(v).replaceAll(',','');return /^[+-]?\d+\.0+$/.test(s)?s.replace(/\.0+$/,''):s;}function num(v){const n=Number(String(v??0).replaceAll(',',''));return Number.isFinite(n)?n:0;}function numericText(v){const s=text(v).replaceAll(',','');return s===''?'':String(Number(s)||0);}function uniq(a){return[...new Set(a)];}function marks(n){return Array(n).fill('?').join(',');}
function dateIso(v){const s=text(v);if(!s)return'';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const n=Number(s);if(Number.isFinite(n)&&n>20000&&n<80000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return d.toISOString().slice(0,10);}return'';}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date());}function now(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Bangkok',dateStyle:'short',timeStyle:'medium'}).format(new Date());}
function strong(v){const s=String(v||'');return s.length>=10&&/[A-Za-z]/.test(s)&&/\d/.test(s);}function hashPassword(v){const salt=randomBytes(16),h=scryptSync(String(v),salt,64);return`scrypt$${salt.toString('hex')}$${h.toString('hex')}`;}function verifyPassword(v,s){try{const [scheme,sa,hh]=String(s||'').split('$');if(scheme!=='scrypt')return false;const exp=Buffer.from(hh,'hex'),act=scryptSync(String(v),Buffer.from(sa,'hex'),exp.length);return exp.length===act.length&&timingSafeEqual(exp,act);}catch{return false;}}function sha(v){return createHash('sha256').update(String(v)).digest('hex');}
function getCookie(req){for(const x of (req.headers.get('cookie')||'').split(';')){const[k,...v]=x.trim().split('=');if(k===COOKIE)return decodeURIComponent(v.join('='));}return'';}function cookie(v,age,secure){return[`${COOKIE}=${encodeURIComponent(v)}`,'Path=/','HttpOnly','SameSite=Strict',secure?'Secure':'',`Max-Age=${Math.max(0,Math.floor(age))}`].filter(Boolean).join('; ');}function checkOrigin(req,url){const o=req.headers.get('origin');if(o&&o!==url.origin)throw pub(403,'Origin not allowed');}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});}function noStore(r){const h=new Headers(r.headers);h.set('cache-control','no-store, max-age=0');h.set('x-content-type-options','nosniff');return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h});}
